FROM node:9.5.0-alpine

# set working directory
RUN mkdir -p /usr/src/react-web
WORKDIR /usr/src/react-web

# add `/usr/src/react-web/node_modules/.bin` to $PATH
ENV PATH /usr/src/react-web/node_modules/.bin:$PATH

# install and cache react-web dependencies
ADD ./frontend/package.json /usr/src/react-web/package.json
RUN npm install --silent
RUN npm install react-scripts@1.1.1 -g --silent

# start app
CMD ["npm", "start"]