version: '3.4'

services:

  react-frontend:
    container_name: react-frontend
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - './frontend:/usr/src/react-web'
      - '/usr/src/react-web/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true